import type { CanvasBlockData } from './types';

export const INITIAL_CANVAS_STRUCTURE: CanvasBlockData[] = [
  {
    id: 'key-partners',
    title: 'Kulcspartnerek',
    description: 'Kik a kulcspartnereink és beszállítóink?',
    color: 'bg-red-100',
    items: [],
  },
  {
    id: 'key-activities',
    title: 'Kulcsfontosságú tevékenységek',
    description: 'Milyen kulcstevékenységeket igényel az értékajánlatunk?',
    color: 'bg-orange-100',
    items: [],
  },
  {
    id: 'main-interventions',
    title: 'Fő beavatkozások',
    description: 'Melyek a legfontosabb stratégiai beavatkozások a célok eléréséhez?',
    color: 'bg-pink-100',
    items: [],
  },
  {
    id: 'key-resources',
    title: 'Kulcsfontosságú erőforrások',
    description: 'Milyen kulcserőforrásokat igényel az értékajánlatunk?',
    color: 'bg-orange-100',
    items: [],
  },
  {
    id: 'new-key-resources',
    title: 'Kulcserőforrások',
    description: 'Milyen további kulcserőforrásokat igényel az értékajánlatunk?',
    color: 'bg-amber-100',
    items: [],
  },
  {
    id: 'value-propositions',
    title: 'Értékajánlatok',
    description: 'Milyen értéket nyújtunk az ügyfélnek?',
    color: 'bg-green-100',
    items: [],
  },
  {
    id: 'customer-relationships',
    title: 'Ügyfélkapcsolatok',
    description: 'Milyen típusú kapcsolatot vár el tőlünk minden ügyfélszegmens?',
    color: 'bg-blue-100',
    items: [],
  },
  {
    id: 'channels',
    title: 'Csatornák',
    description: 'Mely csatornákon keresztül érjük el ügyfeleinket?',
    color: 'bg-blue-100',
    items: [],
  },
  {
    id: 'digital-channels',
    title: 'Digitális Csatornák',
    description: 'Mely online és digitális csatornákat használjuk?',
    color: 'bg-teal-100',
    items: [],
  },
  {
    id: 'customer-segments',
    title: 'Ügyfélszegmensek',
    description: 'Kiknek teremtünk értéket? Kik a legfontosabb ügyfeleink?',
    color: 'bg-purple-100',
    items: [],
  },
  {
    id: 'segments-beneficiaries-customers',
    title: 'Szegmensek, kedvezményezettek, vevők',
    description: 'Kik a célcsoportok, kedvezményezettek és végső vevők?',
    color: 'bg-violet-100',
    items: [],
  },
  {
    id: 'cost-structure',
    title: 'Költségszerkezet',
    description: 'Melyek a legfontosabb költségek, amelyek a modellünkben rejlenek?',
    color: 'bg-yellow-100',
    items: [],
  },
  {
    id: 'revenue-streams',
    title: 'Bevételi források',
    description: 'Milyen értékért hajlandóak fizetni ügyfeleink?',
    color: 'bg-lime-100',
    items: [],
  },
];